export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_ID = "GET_PRODUCT_ID";
export const ADD_CART='ADD_CART';
export const CART_ADD_QUANTITY = "CART_ADD_QUANTITY";
export const CART_REMOVE_QUANTITY = "CART_REMOVE_QUANTITY";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"